import type {ResolvedOptions} from './types';

export const FORBIDDEN_SEQUENCES = [
    '0123456789',
    'abcdefghijklmnopqrstuvwxyz',
    'qwertyuiop',
    'asdfghjkl',
    'zxcvbnm',
    '!@#$%^&*()_+',
];

const COMMON_PASSWORDS = [
    '123456', 'password', '12345678', 'qwerty', '123456789', '12345', '1234',
    '111111', '1234567', 'dragon', '123123', 'baseball', 'abc123', 'football',
    'monkey', 'letmein', '696969', 'shadow', 'master', '666666', 'qwertyuiop',
    '123321', 'mustang', '1234567890', 'michael', '654321', 'pussy', 'superman',
    '1qaz2wsx', '7777777', 'fuckyou', '121212', '000000', 'qazwsx', '123qwe',
    'killer', 'trustno1', 'jordan', 'jennifer', 'zxcvbnm', 'asdfgh', 'hunter',
    'buster', 'soccer', 'harley', 'batman', 'andrew', 'tigger', 'sunshine',
    'iloveyou', 'fuckme', '2000', 'charlie', 'robert', 'thomas', 'hockey',
    'ranger', 'daniel', 'starwars', 'klaster', '112233', 'george', 'asshole',
    'computer', 'michelle', 'jessica', 'pepper', '1111', 'zxcvbn', '555555',
    '11111111', '131313', 'freedom', '777777', 'pass', 'fuck', 'maggie',
    '159753', 'aaaaaa', 'ginger', 'princess', 'joshua', 'cheese', 'amanda',
    'summer', 'love', 'ashley', '6969', 'nicole', 'chelsea', 'biteme',
    'matthew', 'access', 'yankees', '987654321', 'dallas', 'austin', 'thunder',
    'taylor', 'matrix',
];

const FALLBACK_I18N: Record<string, string> = {
    wordMinLength: 'Your password is too short',
    wordMaxLength: 'Your password is too long',
    wordInvalidChar: 'Your password contains an invalid character',
    wordNotEmail: 'Do not use your email as your password',
    wordSimilarToUsername: 'Your password cannot contain your username',
    wordTwoCharacterClasses: 'Use different character classes',
    wordRepetitions: 'Too many repetitions',
    wordSequences: 'Your password contains sequences',
    errorList: 'Errors:',
    veryWeak: 'Very Weak',
    weak: 'Weak',
    normal: 'Normal',
    medium: 'Medium',
    strong: 'Strong',
    veryStrong: 'Very Strong',
};

export const defaultOptions: ResolvedOptions = {
    minChar: 6,
    maxChar: 20,
    usernameField: '#username',
    invalidCharsRegExp: /[\s,'"]/,
    userInputs: [],
    events: ['input', 'change', 'paste'],
    debug: false,
    onLoad: undefined,
    onKeyUp: undefined,
    onScore: undefined,
    zxcvbn: false,
    zxcvbnTerms: [],
    rules: {
        activated: {
            wordNotEmail: true,
            wordMinLength: true,
            wordMaxLength: false,
            wordInvalidChar: false,
            wordSimilarToUsername: true,
            wordSequences: true,
            wordTwoCharacterClasses: true,
            wordRepetitions: true,
            wordLowercase: true,
            wordUppercase: true,
            wordOneNumber: true,
            wordThreeNumbers: true,
            wordOneSpecialChar: true,
            wordTwoSpecialChar: true,
            wordUpperLowerCombo: true,
            wordLetterNumberCombo: true,
            wordLetterNumberCharCombo: true,
            wordIsACommonPassword: true,
        },
        scores: {
            wordNotEmail: -100,
            wordMinLength: -50,
            wordMaxLength: -50,
            wordInvalidChar: -100,
            wordSimilarToUsername: -100,
            wordSequences: -20,
            wordTwoCharacterClasses: 2,
            wordRepetitions: -25,
            wordLowercase: 1,
            wordUppercase: 3,
            wordOneNumber: 3,
            wordThreeNumbers: 5,
            wordOneSpecialChar: 3,
            wordTwoSpecialChar: 5,
            wordUpperLowerCombo: 2,
            wordLetterNumberCombo: 2,
            wordLetterNumberCharCombo: 2,
            wordIsACommonPassword: -100,
        },
        extra: {},
        raisePower: 1.4,
        specialCharClass: '[!,@,#,$,%,^,&,*,?,_,~]',
        commonPasswords: COMMON_PASSWORDS,
    },
    ui: {
        colorClasses: ['danger', 'danger', 'danger', 'warning', 'warning', 'success'],
        showProgressBar: true,
        progressBarEmptyPercentage: 1,
        progressBarMinWidth: 1,
        progressBarMinPercentage: 1,
        progressExtraCssClasses: '',
        progressBarExtraCssClasses: '',
        showVerdicts: true,
        showVerdictsInsideProgressBar: false,
        useVerdictCssClass: false,
        showErrors: false,
        showScore: false,
        showStatus: false,
        showPopover: false,
        popoverPlacement: 'bottom',
        container: null,
        viewports: {},
        scores: [0, 14, 26, 38, 50],
        spanError: (text) => text ? `<span style="color: #d52929">${text}</span>` : '',
        popoverError: (errors) =>
            `<div><ul class="error-list" style="margin-bottom:0">${errors.map(e => `<li>${e}</li>`).join('')}</ul></div>`,
    },
    i18n: {
        t: (key) => FALLBACK_I18N[key] ?? key,
    },
};
